FROM python:2.7-slim

RUN apt update \
    && apt install --no-install-recommends -y bash certbot openssl \
    && apt clean

ADD requirements.txt /usr/local/bin/

RUN pip install -r /usr/local/bin/requirements.txt

ADD setup.py /usr/local/bin/setup
ADD gen_self_signed_cert.sh /usr/local/bin/gen_self_signed_cert
ADD run_admin.sh /run.sh
RUN chmod +x /usr/local/bin/setup /run.sh /usr/local/bin/gen_self_signed_cert

ENV CERTBOT_PORT=80
ENV SETUP_REFRESH_FREQUENCY=86400

CMD ["/run.sh"]