FROM amazonlinux:2

RUN  yum install -y bash python python-pip certbot openssl \
  && yum clean all \
  && rm -rf /var/cache/yum 
  
ADD requirements.txt /usr/local/bin/

RUN pip install -r /usr/local/bin/requirements.txt

ADD *.py /usr/local/bin/
ADD setup.py /usr/local/bin/setup
ADD run_admin_aws.sh /run.sh
RUN chmod +x /usr/local/bin/setup /run.sh

ENV CERTBOT_PORT=80
ENV SETUP_REFRESH_FREQUENCY=86400

CMD ["/run.sh"]