FROM alpine:3.11.2

ENV TERM=xterm

ENV PROFTPD_VERSION 1.3.6c

RUN apk update \
    && apk add --no-cache --virtual .persistent-deps \
      ca-certificates \
      curl \
      gettext \
      bash \
    && apk add --no-cache --virtual .build-deps \
      git \
      build-base \
      libressl-dev \
      zlib-dev

# we use the latest commit from branch 1.3.6 to get the fix for LibreSSL 2.9.x
# https://github.com/proftpd/proftpd/issues/810
RUN git clone -b 1.3.6 https://github.com/proftpd/proftpd.git \
    && cd proftpd \
    && git reset fa4c0ac64cb048ae114beab08fb2ac9abc61b58a --hard

## Note: use the ftp archive when 1.3.6c is released
# RUN curl -fSL ftp://ftp.proftpd.org/distrib/source/proftpd-${PROFTPD_VERSION}.tar.gz -o proftpd.tgz \
#     && tar -xf proftpd.tgz \
#     && rm proftpd.tgz \
#     && mv proftpd-${PROFTPD_VERSION} proftpd

RUN cd proftpd \
    && ./configure \
      --enable-ctrls --enable-openssl --enable-quotatab --enable-nls \
      --with-modules=mod_tls:mod_quotatab:mod_quotatab_file:mod_ifsession:mod_ban:mod_sftp:mod_deflate --enable-nls \
    && make \
    && make install \
    && make clean \
    && cd .. \
    && rm -rf proftpd \
    && apk del .build-deps \
    && rm -rf /var/cache/apk/*

RUN mkdir -p /sslcert /etc/proftpd/ /var/proftpd/home

ADD proftpd* /etc/proftpd/

ADD run_proftpd.sh /
RUN chmod +x /run_proftpd.sh

RUN mkdir -p /etc/proftpd/conf.d

ENV FTP_PORT=21
ENV LIMITS_CONF_FILE=/etc/proftpd/conf.d/limits.conf
ENV PROFTPD_REFRESH_FREQUENCY=600
ENV PASSIVE_PORTS_FROM=30000
ENV SSL_CERT_PATH=/var/ssl/domain
ENV PASSIVE_PORTS_TO=30099
ENV PROFTPD_CONF_FILE=/etc/proftpd/proftpd_ftps.conf
ENV FTPS_REQUIRED=TRUE
ENV FTP_HOME_PATH=/var/proftpd/home
ENV FTP_USERS_FILE=/var/proftpd/ftpusers
ENV SFTP_USERS_FILE=/var/proftpd/sftpusers
ENV ENABLE_FTP_DEFLATE=TRUE
ENV ENABLE_SFTP_COMPRESSION=TRUE

CMD ["/run_proftpd.sh"]
