FROM python:2.7-slim

RUN apt update \
    && apt install --no-install-recommends -y bash certbot openssl \
    && apt clean

ADD requirements.txt /usr/local/bin/

RUN pip install -r /usr/local/bin/requirements.txt

ADD *.py /usr/local/bin/
ADD setup.py /usr/local/bin/setup
ADD run_admin.sh /run.sh
RUN chmod +x /usr/local/bin/setup /run.sh

ENV CERTBOT_PORT=80
ENV SETUP_REFRESH_FREQUENCY=86400
ENV SSL_CERT_PATH=/var/ssl

CMD ["/run.sh"]